---
title: "R Notebook for Probability Exercises"
output: html_notebook
---

 

```{r}
## 1.8 Probability and counting ========

# Page 29: Vectors
v <- c(1,3,5,7,9,11)
v[c(1,3)]
v[-c(1,3)]
v2 <- 1/(1:100)^2

# Page 30 Factorials  
choose(10,2)
choose(1000000,1000)
lchoose(1000000,1000)
factorial(1000)
lfactorial(1000)

# Page 30-31 Sampling and simulation
n <- 10; k <- 6
sample(n,k, replace =TRUE)
sample(letters,k)
sample(5,5,replace=TRUE,prob = c(0.6,0.1,0.1,0.1,0.1))

# Page 31 Matching problem simulation
n <- 10;        # number of cards
r <- 1       # number of times running experiment
results<- replicate(r,sample(n)==(1:n)) # shuffle and count matches
number.successes<-sum(results>=1) # sum number of matches
proportion.matches = number.successes/(r*n) # proportion of matches to total number of experiments

# Page 32 Birthday problem
qbirthday(0.5)        # number of people needed to have probability of at least 50% of at least one match
pbirthday(23,coincident = 3)  # probability of a triple birthday match given 23 people 
b <- sample (365,23,replace=TRUE)  # assign birthdays to 23 people, where each of 365 "days"" has equal probability
table(b)
r <- replicate(10^4, max(table(sample(365,23,replace=TRUE))))
sum(r>=2)/10^4 # how many days had at least two people born on that day, on average after 10^4 runs?

```

```{r}
## 2.10 Conditional probability ========

# Page 80: Simulating the frequentist interpretation
n <- 10^5       #number of families
child1 <- sample(2,n,replace=TRUE)  # let 1 be a girl, 2 be a boy
child2 <- sample(2,n,replace=TRUE)  

n.b <- sum(child1==1) #number times child 1 is a girl
n.ab <- sum(child1==1 & child2 ==1) # number times both children are girls

p.a.given.b <- n.ab/n.b # prob. both girls given child1 is a girl

n.c <- sum(child1==1 | child2 ==1) #number families either child 1 or 2 (or both) is a girl
p.ab.given.c <- n.ab/n.c # prob. both girls given at least one is a girl

# Page 82 Monty Hall simulation
n <- 10^5 #number of times to run simulation
cardoor <- sample(3,n,replace = TRUE) #assign a location for the car
p.success.choose1 <- sum(cardoor==1)/n #if don't switch, choose 1 door, probability of success (about 1/3)

monty <- function() { #create an interactive function
    doors <- 1:3
    cardoor <- sample(doors,1) #random sample of 1:3
    print("Pick a door (enter 1,2 or 3)") #prompt
    chosen<-scan(what=integer(),nlines = 1,quiet=TRUE) #receive choice of door
    if (chosen!=cardoor) montydoor<-doors[-c(chosen,cardoor)] else montydoor <- sample(doors[-chosen],1) #pick Monty's door
    print(paste("Monty opens door ",montydoor,".", sep = ""))
    print("Would you like to switch (y/n)?") #prompt to switch
    reply<- scan(what=character(),nlines=1,quiet =TRUE)
    
    if(substr(reply,1,1)=="y") {  #only change chosen if "y"
      chosen<-doors[-c(chosen,montydoor)]
    }
    
    if(chosen==cardoor) print("Yatze!") else print("Dang.")
    
}
monty()  

```
 
```{r}
## 3.11  Random variables and their distributions ========

#Page 138 Distributions in R
help(distributions)

#Page 138 Binomial distribution
dbinom(3,5,0.2)  # binomial PDF with inputs (k,n,p)
pbinom(3,4,0.2)  # binomial CDF with inputs (k,n,p)
rbinom(10,4,0.5) # rancom set of x binomial of (x,n,p)

#Page 139 Hypergeometric
dhyper(1,5,5,3) # hypergeometric X=k=1 from ~Hypergeometric(w=5,b=5,n=3)

# Page 139 Discrete distributions with finite support
# Use sample function sample (n,k) where n is the distribution and k is the number of elements to choose...but we can make x a vector of values with a corresponding vector, p, of probabilities (so x can be any distribution!)

#example:
x<-c(0,1,5,10) #values
p <-c(0.25,0.5,0.1,0.15) # PMF of x
sample(x,100,prob=p,replace=TRUE) #sample 100 times from distribution'x' 

```

```{r}
## 4.11 Expectation ========

##Page 193 Matching simulation

n <- 100
r <- replicate(10^4,sum(sample(n)==(1:n))) # looking at chance matches of a random sample of a deck of n cards ...
mean(r) # expected number of matches (the mean)

##Page 193 Distinct birthday simulation
 k <- 20 # group of 20 people
 r <- replicate (10^4, {bdays <- sample(365,k,replace = TRUE);
                        length(unique(bdays))}) #we sample k times from 1:365, then remove duplicates with unique(bdays) and length() calculatates the length AFTER duplicates have been removed... so R contains the # of distinct birhtdays
 
 mean(r) # the empirical value with 10^4 trials
365*(1-(364/365)^k) #the theoretic value
```

```{r}
## 5.9 R Continuous and Random Variables  ========

##Page 253 Uniform, Normal, and Expoential distributions
dunif(0.1,0,1) #dunif(x,a,b) is PDF of Unif(a,b) at x
punif(0.5,0,1) #CDF at x=0.5
runif(10,0,1) # generate x=10 random numbers from unif(0,1)

dnorm(0,0,1) #dnorm(x,mu,sd) is PDF of normal(mu,sd) at x ***NOTE: sd NOT variance**
rnorm(10,0,1) #generate 10 random realizations from a standard normal

dexp(3,3) #dexp(x,lamda)

## Page 254 Plots in R
curve(dnorm, from=-3, to=3, n=10) # plot the standard normal from -3 to 3 evaulated at 10 points

x <- seq(-3,3,0.1) #like matlab
y <- dnorm(x,0,1) #so y consists of standard normal evaluated at points x
#plot(x,y)
plot(x,y,type="b", col="red",lty=1, lwd=1)

## Page 254 Universality with Logistic

u<- runif(10^4) # start with random realizations from a uniform distrbution
x <- log(u/(1-u)) # use inverse function to get x values that should resemble a logistic distribution
hist(x, breaks=100) # check that it "looks" like a logistic

y<-rlogis(10^4) # check by more directly generating random realizations from a logistic 
hist(y, breaks=100) # yep looks the same as above

## Page 255 Poisson process simulation

# the times in between arrivals are exponential, so first we generate "interarrival" times as exponential distribution with rate parameter lambda
n<- 50 # could be anything
lambda <- 3 # rate (3 per unit of time)
x <- rexp(n,lambda) 
hist(x) # take a look
t<- cumsum(x) # final step: convert the interarrival times to arrival times using cumulative sum function

x_axis <- seq(1:50)
plot(x_axis,t)
```

```{r}
## 6.9 R Momens  ========

##Page 293 Functions  

M <- function(t) {exp(t^2/2)} #define M to be a function M(t), this is the MFG for standard normal
curve(M,from = -3,to=3) # check out a plot of the curve for range of t

g <- function(t,mean=0,sd=1) {exp(mean*t + sd^2*t^2/2)} # general MGF for N(mean,sd^2), and notice we set useful variable names and default values
g(t=1,mean=2,sd=3)

##Page 294 Moments

help(dnorm)
g <- function(x) x^6*dnorm(x) # recall dnorm give the pdf 
integrate (g, lower=-Inf, upper=Inf) #do the "integral" numerically!  using the integrate command

#check that the 2nd moment, and variance, of a Unif(-1,1) r.v. is 1/3
h<-function(x) x^2*dunif(x,-1,1) # x^2 so second moment
integrate(h, lower=-1, upper=1)

g<-function(k) k^2*dpois(k,7) #2nd moment of X~Pois(7)
sum(g(0:100)) #using sum for discrete series of r.v.s

# finding the moment of a sample of 100 i.i.d.s ....
x <- rnorm(100)
mean(x^6) # 6th sample moment

# R built-in functions for mean, variance and sd
z <- rnorm(100)
mean(z)
var(z)
sd(z)

# Define function for skewness
skew <-
    function(x) {
        central.moment <-
            mean((x-mean(x))^3)
            central.moment/(sd(x)^3)
    }
skew(x)

# Define a function for kurtosis

#kurt <
#   function(x) {
#        centralmoment < mean((xmean(x))4)
        
#    }

```

