---
title: "R Notebook"
output: html_notebook
---
 

```{r}

# +++++++++++++++++ #
#                   # 
#    LIBRARIES
#                   #
# +++++++++++++++++ #

# Installation of required packages

install.packages("tableone")
install.packages("Matching")
install.packages("MatchIt")

install.packages("ipw")
install.packages("survey")

install.packages("data.table")


# Load libraries


library(tableone)
library(Matching)
library(MatchIt)

library(ipw)
library(survey)

library(utils)
library(dplyr)
library(data.table) 


#Load data

data(lalonde)

 
dat <- lalonde
View(dat)


```

```{r}
# +++++++++++++++++ #
#                   # 
# QUESTION 1: 
# Fit a propensity score model. Use a logistic regression model, 
# where the outcome is treatment. Include the 8 confounding variables in
# the model as predictors, with no interaction terms or non-linear terms (such as
# squared terms). Obtain the propensity score for each subject. Next, obtain the
# inverse probability of treatment weights for each subject.  
#
# What are the minimum and maximum weights?    
#                   #
# +++++++++++++++++ #

# list covariates in one group
xvars <- c("age","educ","race","married","nodegree","re74","re75")

# fit a propensity model (likelihood of treatment = outcome of interest)
pmodel <- glm(treat ~ age + educ + race + married + nodegree + re74 + re75,
              family = binomial(),
              data =dat)

# pull out propensity scores
#pscores <- pmodel$fitted.values
ps <- predict(pmodel, type = "response")

# create weights
weight <- ifelse(pmodel$treat==1,1/(ps),1/(1-ps))

#apply weights to data
weighted.dat <- svydesign(ids = ~1, data = dat, weights = ~weight)


```
```{r}
summary(ps)
```


```{r}
# create a 'table one' 
weighted.table <- svyCreateTableOne(vars= xvars, 
                                    strata = "treat",
                                    data = weighted.dat)
```




```{r}

# +++++++++++++++++ #
#                   # 
# QUESTION 3:
# Fit a propensity score model. 
# Include the 8 confounding variables in the model as predictors, 
# with no interaction terms or non-linear terms (such as squared terms). 

# What are the minimum and maximum values of the estimated propensity score? 
#                   #
# +++++++++++++++++ #


# Use a logistic regression model, where the outcome is treatment. 
psmodel <- glm(treat~age + educ + race + married + nodegree + re74 + re75,
               family=binomial(),
               data=dat)
#summary(psmodel)


# Obtain the propensity score for each subject.
pscore<-psmodel$fitted.values

print(min(pscore))
print(max(pscore))
```
```{r}

# +++++++++++++++++ #
#                   # 
# QUESTION 4 and 5:
# Now carry out propensity score matching using the Match function.  
# What is the standardized difference for married?
#                   #
# +++++++++++++++++ #

set.seed(931139)

# Use options to specify pair matching, without replacement, no caliper. 
psmatch <- Match(Tr=dat$treat,
                 M=1,
                 X=pscore, # Match on the propensity score itself, not logit of the propensity score.  
                 replace=FALSE)

# organize tableOne for matched data
matched <- dat[unlist(psmatch[c("index.treated","index.control")]),]
matchedtab1 <- CreateTableOne(vars=xvars, 
                              strata = "treat",
                              data=matched,
                              test=FALSE)
print(matchedtab1, smd=TRUE)

```
```{r}
# +++++++++++++++++ #
#                   # 
# QUESTION 6:
# Re-do the matching, but use a caliper this time. Set the caliper=0.1   
# How many matched pairs are there?
#                   #
# +++++++++++++++++ #

set.seed(931139)

# Use options to specify pair matching, without replacement, WITH caliper 
psmatch <- Match(Tr=dat$treat,
                 M=1,
                 X=pscore, # Match on the propensity score itself, not logit of the propensity score.  
                 replace=FALSE,
                 caliper = 0.1)

# organize tableOne for matched data
matched2 <- dat[unlist(psmatch[c("index.treated","index.control")]),]
matchedtab2 <- CreateTableOne(vars=xvars, 
                              strata = "treat",
                              data=matched2,
                              test=FALSE)
print(matchedtab2, smd=TRUE)
```


```{r}

# +++++++++++++++++ #
#                   # 
# QUESTION 7:
# For the matched data, what is 
# the mean of real earnings in 1978 for treated subjects minus
# the mean of real earnings in 1978 for untreated subjects? 
#                   #
# +++++++++++++++++ #

result<-matched2 %>%
  group_by(treat) %>%
  summarize(mean_size = mean(re78))

# difference
result[result$treat==1,"mean_size"] - result[result$treat==0,"mean_size"]

```
```{r}
# +++++++++++++++++ #
#                   # 
# QUESTION 8:
# Carry out a paired t-test for the effect of
# treatment on earnings. 
# What are the values of the 95% confidence interval? 
#                   #
# +++++++++++++++++ #

# compare treated re78 to control re78

treated <- matched2 %>%
    filter(treat==1)  
    
    
control<- matched2 %>%
    filter(treat==0)  

t.test(treated$re78,control$re78,paired=TRUE)

```
